
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Deskripsi Website      <small><?= cclang('detail', ['Deskripsi Website']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tb_deskripsi_web'); ?>">Deskripsi Website</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Deskripsi Website</h3>
                     <h5 class="widget-user-desc">Detail Deskripsi Website</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tb_deskripsi_web" id="form_tb_deskripsi_web" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Des Web </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->id_des_web); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Web </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->nama_web); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Title </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->title_web); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Deskripsi </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->deskripsi_web); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Author </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->author); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Kepala </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->nama_kepala); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Foto Kepala </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tb_deskripsi_web->foto_kepala)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->foto_kepala; ?>">
                                <img src="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->foto_kepala; ?>" class="image-responsive" alt="image tb_deskripsi_web" title="foto_kepala tb_deskripsi_web" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tb_deskripsi_web/' . $tb_deskripsi_web->foto_kepala; ?>">
                                 <img src="<?= get_icon_file($tb_deskripsi_web->foto_kepala); ?>" class="image-responsive" alt="image tb_deskripsi_web" title="foto_kepala <?= $tb_deskripsi_web->foto_kepala; ?>" width="40px"> 
                               <?= $tb_deskripsi_web->foto_kepala ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alamat Kantor </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->alamat); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Telepon </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->tlpon); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Meta Tambahan </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->meta_tambahan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Developer </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->nama_deveoper); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tahun Dibangun </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_deskripsi_web->tahun_bangun); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Ikon Aplikasi </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tb_deskripsi_web->ikon_web)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->ikon_web; ?>">
                                <img src="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->ikon_web; ?>" class="image-responsive" alt="image tb_deskripsi_web" title="ikon_web tb_deskripsi_web" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tb_deskripsi_web/' . $tb_deskripsi_web->ikon_web; ?>">
                                 <img src="<?= get_icon_file($tb_deskripsi_web->ikon_web); ?>" class="image-responsive" alt="image tb_deskripsi_web" title="ikon_web <?= $tb_deskripsi_web->ikon_web; ?>" width="40px"> 
                               <?= $tb_deskripsi_web->ikon_web ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Logo Aplikasi </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tb_deskripsi_web->logo_web)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->logo_web; ?>">
                                <img src="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->logo_web; ?>" class="image-responsive" alt="image tb_deskripsi_web" title="logo_web tb_deskripsi_web" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tb_deskripsi_web/' . $tb_deskripsi_web->logo_web; ?>">
                                 <img src="<?= get_icon_file($tb_deskripsi_web->logo_web); ?>" class="image-responsive" alt="image tb_deskripsi_web" title="logo_web <?= $tb_deskripsi_web->logo_web; ?>" width="40px"> 
                               <?= $tb_deskripsi_web->logo_web ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                      
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tb_deskripsi_web_update', function() use ($tb_deskripsi_web){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tb_deskripsi_web (Ctrl+e)" href="<?= site_url('administrator/tb_deskripsi_web/edit/'.$tb_deskripsi_web->id_des_web); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tb Deskripsi Web']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tb_deskripsi_web/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tb Deskripsi Web']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
