
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Tb_deskripsi_web/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('tb_deskripsi_web') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('tb_deskripsi_web') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('tb_deskripsi_web_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('tb_deskripsi_web')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/tb_deskripsi_web/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('tb_deskripsi_web')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('tb_deskripsi_web_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('tb_deskripsi_web') ?>']); ?>" href="<?= site_url('administrator/tb_deskripsi_web/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('tb_deskripsi_web_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('tb_deskripsi_web') ?>']); ?>" href="<?= site_url('administrator/tb_deskripsi_web/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('tb_deskripsi_web') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('tb_deskripsi_web')]); ?>  <i class="label bg-yellow"><?= $tb_deskripsi_web_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tb_deskripsi_web" id="form_tb_deskripsi_web" action="<?= base_url('administrator/tb_deskripsi_web/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th> <?= cclang('nama_web') ?></th>
                           <th> <?= cclang('title_web') ?></th>
                           <th> <?= cclang('author') ?></th>
                           <th> <?= cclang('nama_kepala') ?></th>
                           <th> <?= cclang('nama_deveoper') ?></th>
                           <th> <?= cclang('tahun_bangun') ?></th>
                           <th> <?= cclang('ikon_web') ?></th>
                           <th> <?= cclang('logo_web') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_tb_deskripsi_web">
                     <?php foreach($tb_deskripsi_webs as $tb_deskripsi_web): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $tb_deskripsi_web->id_des_web; ?>">
                           </td>
                                                       
                           <td><?= _ent($tb_deskripsi_web->nama_web); ?></td> 
                           <td><?= _ent($tb_deskripsi_web->title_web); ?></td> 
                           <td><?= _ent($tb_deskripsi_web->author); ?></td> 
                           <td><?= _ent($tb_deskripsi_web->nama_kepala); ?></td> 
                           <td><?= _ent($tb_deskripsi_web->nama_deveoper); ?></td> 
                           <td><?= _ent($tb_deskripsi_web->tahun_bangun); ?></td> 
                           <td>
                              <?php if (!empty($tb_deskripsi_web->ikon_web)): ?>
                                <?php if (is_image($tb_deskripsi_web->ikon_web)): ?>
                                <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->ikon_web; ?>">
                                  <img src="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->ikon_web; ?>" class="image-responsive" alt="image tb_deskripsi_web" title="ikon_web tb_deskripsi_web" width="40px">
                                </a>
                                <?php else: ?>
                                  <a href="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->ikon_web; ?>">
                                   <img src="<?= get_icon_file($tb_deskripsi_web->ikon_web); ?>" class="image-responsive image-icon" alt="image tb_deskripsi_web" title="ikon_web <?= $tb_deskripsi_web->ikon_web; ?>" width="40px"> 
                                 </a>
                                <?php endif; ?>
                              <?php endif; ?>
                           </td>
                            
                           <td>
                              <?php if (!empty($tb_deskripsi_web->logo_web)): ?>
                                <?php if (is_image($tb_deskripsi_web->logo_web)): ?>
                                <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->logo_web; ?>">
                                  <img src="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->logo_web; ?>" class="image-responsive" alt="image tb_deskripsi_web" title="logo_web tb_deskripsi_web" width="40px">
                                </a>
                                <?php else: ?>
                                  <a href="<?= BASE_URL . 'uploads/tb_deskripsi_web/' . $tb_deskripsi_web->logo_web; ?>">
                                   <img src="<?= get_icon_file($tb_deskripsi_web->logo_web); ?>" class="image-responsive image-icon" alt="image tb_deskripsi_web" title="logo_web <?= $tb_deskripsi_web->logo_web; ?>" width="40px"> 
                                 </a>
                                <?php endif; ?>
                              <?php endif; ?>
                           </td>
                            
                           <td width="200">
                            
                                                              <?php is_allowed('tb_deskripsi_web_view', function() use ($tb_deskripsi_web){?>
                                 
                              <a href="<?= site_url('administrator/tb_deskripsi_web/view/' . $tb_deskripsi_web->id_des_web); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('tb_deskripsi_web_update', function() use ($tb_deskripsi_web){?>
                              <a href="<?= site_url('administrator/tb_deskripsi_web/edit/' . $tb_deskripsi_web->id_des_web); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('tb_deskripsi_web_delete', function() use ($tb_deskripsi_web){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/tb_deskripsi_web/delete/' . $tb_deskripsi_web->id_des_web); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($tb_deskripsi_web_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Deskripsi Website data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'nama_web' ? 'selected' :''; ?> value="nama_web">Nama Web</option>
                           <option <?= $this->input->get('f') == 'title_web' ? 'selected' :''; ?> value="title_web">Title</option>
                           <option <?= $this->input->get('f') == 'author' ? 'selected' :''; ?> value="author">Author</option>
                           <option <?= $this->input->get('f') == 'nama_kepala' ? 'selected' :''; ?> value="nama_kepala">Nama Kepala</option>
                           <option <?= $this->input->get('f') == 'nama_deveoper' ? 'selected' :''; ?> value="nama_deveoper">Nama Developer</option>
                           <option <?= $this->input->get('f') == 'tahun_bangun' ? 'selected' :''; ?> value="tahun_bangun">Tahun Dibangun</option>
                           <option <?= $this->input->get('f') == 'ikon_web' ? 'selected' :''; ?> value="ikon_web">Ikon Aplikasi</option>
                           <option <?= $this->input->get('f') == 'logo_web' ? 'selected' :''; ?> value="logo_web">Logo Aplikasi</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/tb_deskripsi_web');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_tb_deskripsi_web').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/tb_deskripsi_web/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>