
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Tb_halaman/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= cclang('tb_halaman') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('tb_halaman') ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('tb_halaman_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', [cclang('tb_halaman')]); ?>  (Ctrl+a)" href="<?=  site_url('administrator/tb_halaman/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', [cclang('tb_halaman')]); ?></a>
                        <?php }) ?>
                        <?php is_allowed('tb_halaman_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('tb_halaman') ?>']); ?>" href="<?= site_url('administrator/tb_halaman/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('tb_halaman_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf <?= cclang('tb_halaman') ?>']); ?>" href="<?= site_url('administrator/tb_halaman/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= cclang('tb_halaman') ?></h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', [cclang('tb_halaman')]); ?>  <i class="label bg-yellow"><?= $tb_halaman_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tb_halaman" id="form_tb_halaman" action="<?= base_url('administrator/tb_halaman/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th> <?= cclang('judul_halaman') ?></th>
                           <th> <?= cclang('kategori_halaman') ?></th>
                           <th> <?= cclang('jenis_template') ?></th>
                           <th> <?= cclang('gambar_halaman') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_tb_halaman">
                     <?php foreach($tb_halamans as $tb_halaman): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $tb_halaman->id_halaman; ?>">
                           </td>
                                                       
                           <td><?= _ent($tb_halaman->judul_halaman); ?></td> 
                           <td><?php if  ($tb_halaman->kategori_halaman) {

                              echo anchor('administrator/tb_kategori_halaman/view/'.$tb_halaman->kategori_halaman.'?popup=show', $tb_halaman->tb_kategori_halaman_nama_kategori_halaman, ['class' => 'popup-view']); }?> </td>
                             
                           <td><?php if  ($tb_halaman->jenis_template) {

                              echo anchor('administrator/tb_template/view/'.$tb_halaman->jenis_template.'?popup=show', $tb_halaman->tb_template_nama_template, ['class' => 'popup-view']); }?> </td>
                             
                           <td>
                              <?php if (!empty($tb_halaman->gambar_halaman)): ?>
                                <?php if (is_image($tb_halaman->gambar_halaman)): ?>
                                <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_halaman/' . $tb_halaman->gambar_halaman; ?>">
                                  <img src="<?= BASE_URL . 'uploads/tb_halaman/' . $tb_halaman->gambar_halaman; ?>" class="image-responsive" alt="image tb_halaman" title="gambar_halaman tb_halaman" width="40px">
                                </a>
                                <?php else: ?>
                                  <a href="<?= BASE_URL . 'uploads/tb_halaman/' . $tb_halaman->gambar_halaman; ?>">
                                   <img src="<?= get_icon_file($tb_halaman->gambar_halaman); ?>" class="image-responsive image-icon" alt="image tb_halaman" title="gambar_halaman <?= $tb_halaman->gambar_halaman; ?>" width="40px"> 
                                 </a>
                                <?php endif; ?>
                              <?php endif; ?>
                           </td>
                            
                           <td width="200">
                            
                                                              <?php is_allowed('tb_halaman_view', function() use ($tb_halaman){?>
                                 <a href="<?= site_url('administrator/tb_halaman/single_pdf/' .$tb_halaman->id_halaman); ?>" class="label-default"><i class="fa fa-file-pdf-o"></i> <?= cclang('PDF') ?>
                              <a href="<?= site_url('administrator/tb_halaman/view/' . $tb_halaman->id_halaman); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('tb_halaman_update', function() use ($tb_halaman){?>
                              <a href="<?= site_url('administrator/tb_halaman/edit/' . $tb_halaman->id_halaman); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('tb_halaman_delete', function() use ($tb_halaman){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/tb_halaman/delete/' . $tb_halaman->id_halaman); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($tb_halaman_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Halaman data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  
                  test
                   <?php foreach (db_get_all_data('tb_kategori_halaman') as $row): ?>
                                   
                                       <?php
                                       if ($row->nama_kategori_halaman=='Kontak'){
                                          echo $row->nama_kategori_halaman.'<br>';
                                           foreach (db_get_all_data('tb_kategori_halaman') as $row2):
                                            echo  '<b>&nbsp;- '.$row2->nama_kategori_halaman.'</b><br>';
                                            endforeach;
                                       }  else{
                                           echo $row->nama_kategori_halaman.'<br>';
                                       }  
                                       ?>
                                    <?php endforeach; ?> 
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                                                     <option value="delete">Delete</option>
                                                  </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'judul_halaman' ? 'selected' :''; ?> value="judul_halaman">Judul Halaman</option>
                           <option <?= $this->input->get('f') == 'kategori_halaman' ? 'selected' :''; ?> value="kategori_halaman">Kategori Halaman</option>
                           <option <?= $this->input->get('f') == 'jenis_template' ? 'selected' :''; ?> value="jenis_template">Jenis Template</option>
                           <option <?= $this->input->get('f') == 'gambar_halaman' ? 'selected' :''; ?> value="gambar_halaman">Gambar Yg Disipkan</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/tb_halaman');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_tb_halaman').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/tb_halaman/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>