
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Halaman      <small><?= cclang('detail', ['Halaman']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tb_halaman'); ?>">Halaman</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Halaman</h3>
                     <h5 class="widget-user-desc">Detail Halaman</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tb_halaman" id="form_tb_halaman" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID Hal </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_halaman->id_halaman); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Judul Halaman </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_halaman->judul_halaman); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Isi Halaman </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_halaman->isi_halaman); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Author </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_halaman->author_halaman); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kategori Halaman </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_halaman->tb_kategori_halaman_nama_kategori_halaman); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Template </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_halaman->tb_template_nama_template); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Gambar Yg Disipkan </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tb_halaman->gambar_halaman)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_halaman/' . $tb_halaman->gambar_halaman; ?>">
                                <img src="<?= BASE_URL . 'uploads/tb_halaman/' . $tb_halaman->gambar_halaman; ?>" class="image-responsive" alt="image tb_halaman" title="gambar_halaman tb_halaman" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tb_halaman/' . $tb_halaman->gambar_halaman; ?>">
                                 <img src="<?= get_icon_file($tb_halaman->gambar_halaman); ?>" class="image-responsive" alt="image tb_halaman" title="gambar_halaman <?= $tb_halaman->gambar_halaman; ?>" width="40px"> 
                               <?= $tb_halaman->gambar_halaman ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Created At </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_halaman->created_at); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Updated At </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_halaman->updated_at); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tb_halaman_update', function() use ($tb_halaman){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tb_halaman (Ctrl+e)" href="<?= site_url('administrator/tb_halaman/edit/'.$tb_halaman->id_halaman); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tb Halaman']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tb_halaman/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tb Halaman']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
