
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Publikasi Informasi      <small><?= cclang('detail', ['Publikasi Informasi']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tb_publikasi'); ?>">Publikasi Informasi</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Publikasi Informasi</h3>
                     <h5 class="widget-user-desc">Detail Publikasi Informasi</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tb_publikasi" id="form_tb_publikasi" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Publikasi </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_publikasi->id_publikasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kategori </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_publikasi->tb_kategori_publikasi_nama_kat_pub); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Judul </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_publikasi->judul_publikasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Isi Konten </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_publikasi->deskripsi_publikasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Gambar Konten </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tb_publikasi->gambar_publikasi)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_publikasi/' . $tb_publikasi->gambar_publikasi; ?>">
                                <img src="<?= BASE_URL . 'uploads/tb_publikasi/' . $tb_publikasi->gambar_publikasi; ?>" class="image-responsive" alt="image tb_publikasi" title="gambar_publikasi tb_publikasi" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tb_publikasi/' . $tb_publikasi->gambar_publikasi; ?>">
                                 <img src="<?= get_icon_file($tb_publikasi->gambar_publikasi); ?>" class="image-responsive" alt="image tb_publikasi" title="gambar_publikasi <?= $tb_publikasi->gambar_publikasi; ?>" width="40px"> 
                               <?= $tb_publikasi->gambar_publikasi ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Author </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_publikasi->author_publikasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sumber Publikasi </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_publikasi->sumber_publikasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Publikasi </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_publikasi->aktif_publikasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Created At </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_publikasi->created_at); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tb_publikasi_update', function() use ($tb_publikasi){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tb_publikasi (Ctrl+e)" href="<?= site_url('administrator/tb_publikasi/edit/'.$tb_publikasi->id_publikasi); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tb Publikasi']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tb_publikasi/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tb Publikasi']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
