
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Publikasi Dokumen      <small><?= cclang('detail', ['Publikasi Dokumen']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tb_file_publikasi'); ?>">Publikasi Dokumen</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Publikasi Dokumen</h3>
                     <h5 class="widget-user-desc">Detail Publikasi Dokumen</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tb_file_publikasi" id="form_tb_file_publikasi" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id File Publikasi </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_file_publikasi->id_file_publikasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Judul File Dokumentasi </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_file_publikasi->judul_file_pub); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Dokumen </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_file_publikasi->tb_kategori_file_nama_kat_file); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> File Upload </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tb_file_publikasi->file_pub)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_file_publikasi/' . $tb_file_publikasi->file_pub; ?>">
                                <img src="<?= BASE_URL . 'uploads/tb_file_publikasi/' . $tb_file_publikasi->file_pub; ?>" class="image-responsive" alt="image tb_file_publikasi" title="file_pub tb_file_publikasi" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tb_file_publikasi/' . $tb_file_publikasi->file_pub; ?>">
                                 <img src="<?= get_icon_file($tb_file_publikasi->file_pub); ?>" class="image-responsive" alt="image tb_file_publikasi" title="file_pub <?= $tb_file_publikasi->file_pub; ?>" width="40px"> 
                               <?= $tb_file_publikasi->file_pub ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Deskripsi Dokumen </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_file_publikasi->deskripsi_pub); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sumber </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_file_publikasi->sumber); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Created At </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_file_publikasi->created_at); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tb_file_publikasi_update', function() use ($tb_file_publikasi){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tb_file_publikasi (Ctrl+e)" href="<?= site_url('administrator/tb_file_publikasi/edit/'.$tb_file_publikasi->id_file_publikasi); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tb File Publikasi']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tb_file_publikasi/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tb File Publikasi']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
