
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Gambar Slider      <small><?= cclang('detail', ['Gambar Slider']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tb_slider'); ?>">Gambar Slider</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Gambar Slider</h3>
                     <h5 class="widget-user-desc">Detail Gambar Slider</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tb_slider" id="form_tb_slider" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Slider </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_slider->id_slider); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Gambar Slider </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tb_slider->gambar_slider)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_slider/' . $tb_slider->gambar_slider; ?>">
                                <img src="<?= BASE_URL . 'uploads/tb_slider/' . $tb_slider->gambar_slider; ?>" class="image-responsive" alt="image tb_slider" title="gambar_slider tb_slider" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tb_slider/' . $tb_slider->gambar_slider; ?>">
                                 <img src="<?= get_icon_file($tb_slider->gambar_slider); ?>" class="image-responsive" alt="image tb_slider" title="gambar_slider <?= $tb_slider->gambar_slider; ?>" width="40px"> 
                               <?= $tb_slider->gambar_slider ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_slider->status); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tb_slider_update', function() use ($tb_slider){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tb_slider (Ctrl+e)" href="<?= site_url('administrator/tb_slider/edit/'.$tb_slider->id_slider); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tb Slider']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tb_slider/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tb Slider']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
