
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Kerjasama (TKKSD)      <small><?= cclang('detail', ['Kerjasama (TKKSD)']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tb_tkksd'); ?>">Kerjasama (TKKSD)</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Kerjasama (TKKSD)</h3>
                     <h5 class="widget-user-desc">Detail Kerjasama (TKKSD)</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tb_tkksd" id="form_tb_tkksd" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nomor </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->no_tkksd); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Kerjasama </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->tanggal_tkksd); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Judul Kesepakatan (Kerjasama) </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->judul_tkksd); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kategori </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->tb_kategori_tkksd_nama_kat_tkksd); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Deskripsi </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->deskripsi_tkksd); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pihak 1 (Dalam Kerjasama) </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->pihak1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pihak 2 (Dalam Kerjasama) </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->pihak2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ruang Lingkup </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->ruang_lingkup); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Lampiran Dokumen (tidak Dipublikasikan) </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tb_tkksd->dokumen_tkksd)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_tkksd/' . $tb_tkksd->dokumen_tkksd; ?>">
                                <img src="<?= BASE_URL . 'uploads/tb_tkksd/' . $tb_tkksd->dokumen_tkksd; ?>" class="image-responsive" alt="image tb_tkksd" title="dokumen_tkksd tb_tkksd" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tb_tkksd/' . $tb_tkksd->dokumen_tkksd; ?>">
                                 <img src="<?= get_icon_file($tb_tkksd->dokumen_tkksd); ?>" class="image-responsive" alt="image tb_tkksd" title="dokumen_tkksd <?= $tb_tkksd->dokumen_tkksd; ?>" width="40px"> 
                               <?= $tb_tkksd->dokumen_tkksd ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Lampiran Dokumen (untuk Dipublikasikan) </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tb_tkksd->gambar_tkksd)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tb_tkksd/' . $tb_tkksd->gambar_tkksd; ?>">
                                <img src="<?= BASE_URL . 'uploads/tb_tkksd/' . $tb_tkksd->gambar_tkksd; ?>" class="image-responsive" alt="image tb_tkksd" title="gambar_tkksd tb_tkksd" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tb_tkksd/' . $tb_tkksd->gambar_tkksd; ?>">
                                 <img src="<?= get_icon_file($tb_tkksd->gambar_tkksd); ?>" class="image-responsive" alt="image tb_tkksd" title="gambar_tkksd <?= $tb_tkksd->gambar_tkksd; ?>" width="40px"> 
                               <?= $tb_tkksd->gambar_tkksd ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jangka Waktu (Awal) </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->jangka_wktu_awal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jangka Waktu (Akhir) </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->jangka_wktu_akhir); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OPD/PD Pemrakarsa </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->tb_daftar_pd_nama_pede); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Keterangan Lainnya </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->keterangan_lainnya); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sumber </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->sumber_tkksd); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?= _ent($tb_tkksd->status_tkksd); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tb_tkksd_update', function() use ($tb_tkksd){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tb_tkksd (Ctrl+e)" href="<?= site_url('administrator/tb_tkksd/edit/'.$tb_tkksd->id_tkksd); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tb Tkksd']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tb_tkksd/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tb Tkksd']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
